"""Initial migration with email_verified

Revision ID: f66f04af562e
Revises: 
Create Date: 2026-01-14 14:36:31.372823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f66f04af562e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cover_letter_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('interview_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('interview_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('feedback', sa.Text(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('feedback')
        batch_op.drop_column('interview_notes')
        batch_op.drop_column('interview_date')
        batch_op.drop_column('cover_letter_path')
        batch_op.drop_column('resume_path')

    # ### end Alembic commands ###
